// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yvv4git/go-juggler-mcp/internal/ports (interfaces: BrowserClient,Filesystem)
//
// Generated by this command:
//
//	mockgen -package=core -destination=internal/core/server_mock.go github.com/yvv4git/go-juggler-mcp/internal/ports BrowserClient,Filesystem
//

// Package core is a generated GoMock package.
package core

import (
	context "context"
	reflect "reflect"

	browser "github.com/yvv4git/go-juggler/browser"
	gomock "go.uber.org/mock/gomock"
)

// MockBrowserClient is a mock of BrowserClient interface.
type MockBrowserClient struct {
	ctrl     *gomock.Controller
	recorder *MockBrowserClientMockRecorder
	isgomock struct{}
}

// MockBrowserClientMockRecorder is the mock recorder for MockBrowserClient.
type MockBrowserClientMockRecorder struct {
	mock *MockBrowserClient
}

// NewMockBrowserClient creates a new mock instance.
func NewMockBrowserClient(ctrl *gomock.Controller) *MockBrowserClient {
	mock := &MockBrowserClient{ctrl: ctrl}
	mock.recorder = &MockBrowserClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrowserClient) EXPECT() *MockBrowserClientMockRecorder {
	return m.recorder
}

// Back mocks base method.
func (m *MockBrowserClient) Back(ctx context.Context, tabID, sessionKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Back", ctx, tabID, sessionKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Back indicates an expected call of Back.
func (mr *MockBrowserClientMockRecorder) Back(ctx, tabID, sessionKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Back", reflect.TypeOf((*MockBrowserClient)(nil).Back), ctx, tabID, sessionKey)
}

// Click mocks base method.
func (m *MockBrowserClient) Click(ctx context.Context, tabID, sessionKey, ref, selector string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Click", ctx, tabID, sessionKey, ref, selector)
	ret0, _ := ret[0].(error)
	return ret0
}

// Click indicates an expected call of Click.
func (mr *MockBrowserClientMockRecorder) Click(ctx, tabID, sessionKey, ref, selector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Click", reflect.TypeOf((*MockBrowserClient)(nil).Click), ctx, tabID, sessionKey, ref, selector)
}

// CloseSession mocks base method.
func (m *MockBrowserClient) CloseSession(ctx context.Context, sessionKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSession", ctx, sessionKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSession indicates an expected call of CloseSession.
func (mr *MockBrowserClientMockRecorder) CloseSession(ctx, sessionKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSession", reflect.TypeOf((*MockBrowserClient)(nil).CloseSession), ctx, sessionKey)
}

// CloseTab mocks base method.
func (m *MockBrowserClient) CloseTab(ctx context.Context, tabID, sessionKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseTab", ctx, tabID, sessionKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseTab indicates an expected call of CloseTab.
func (mr *MockBrowserClientMockRecorder) CloseTab(ctx, tabID, sessionKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseTab", reflect.TypeOf((*MockBrowserClient)(nil).CloseTab), ctx, tabID, sessionKey)
}

// Evaluate mocks base method.
func (m *MockBrowserClient) Evaluate(ctx context.Context, tabID, sessionKey, expression string) (*browser.EvaluateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", ctx, tabID, sessionKey, expression)
	ret0, _ := ret[0].(*browser.EvaluateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockBrowserClientMockRecorder) Evaluate(ctx, tabID, sessionKey, expression any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockBrowserClient)(nil).Evaluate), ctx, tabID, sessionKey, expression)
}

// Forward mocks base method.
func (m *MockBrowserClient) Forward(ctx context.Context, tabID, sessionKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Forward", ctx, tabID, sessionKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Forward indicates an expected call of Forward.
func (mr *MockBrowserClientMockRecorder) Forward(ctx, tabID, sessionKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Forward", reflect.TypeOf((*MockBrowserClient)(nil).Forward), ctx, tabID, sessionKey)
}

// Health mocks base method.
func (m *MockBrowserClient) Health(ctx context.Context) (*browser.HealthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health", ctx)
	ret0, _ := ret[0].(*browser.HealthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Health indicates an expected call of Health.
func (mr *MockBrowserClientMockRecorder) Health(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockBrowserClient)(nil).Health), ctx)
}

// Links mocks base method.
func (m *MockBrowserClient) Links(ctx context.Context, tabID, sessionKey string, limit, offset int) (*browser.LinksResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Links", ctx, tabID, sessionKey, limit, offset)
	ret0, _ := ret[0].(*browser.LinksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Links indicates an expected call of Links.
func (mr *MockBrowserClientMockRecorder) Links(ctx, tabID, sessionKey, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Links", reflect.TypeOf((*MockBrowserClient)(nil).Links), ctx, tabID, sessionKey, limit, offset)
}

// ListTabs mocks base method.
func (m *MockBrowserClient) ListTabs(ctx context.Context, sessionKey string) (*browser.ListTabsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTabs", ctx, sessionKey)
	ret0, _ := ret[0].(*browser.ListTabsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTabs indicates an expected call of ListTabs.
func (mr *MockBrowserClientMockRecorder) ListTabs(ctx, sessionKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTabs", reflect.TypeOf((*MockBrowserClient)(nil).ListTabs), ctx, sessionKey)
}

// Navigate mocks base method.
func (m *MockBrowserClient) Navigate(ctx context.Context, tabID, sessionKey, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Navigate", ctx, tabID, sessionKey, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// Navigate indicates an expected call of Navigate.
func (mr *MockBrowserClientMockRecorder) Navigate(ctx, tabID, sessionKey, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Navigate", reflect.TypeOf((*MockBrowserClient)(nil).Navigate), ctx, tabID, sessionKey, url)
}

// NetworkRequests mocks base method.
func (m *MockBrowserClient) NetworkRequests(ctx context.Context, tabID, sessionKey string) ([]browser.ResourceEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkRequests", ctx, tabID, sessionKey)
	ret0, _ := ret[0].([]browser.ResourceEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NetworkRequests indicates an expected call of NetworkRequests.
func (mr *MockBrowserClientMockRecorder) NetworkRequests(ctx, tabID, sessionKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkRequests", reflect.TypeOf((*MockBrowserClient)(nil).NetworkRequests), ctx, tabID, sessionKey)
}

// OpenTab mocks base method.
func (m *MockBrowserClient) OpenTab(ctx context.Context, sessionKey, url string) (*browser.TabResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenTab", ctx, sessionKey, url)
	ret0, _ := ret[0].(*browser.TabResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenTab indicates an expected call of OpenTab.
func (mr *MockBrowserClientMockRecorder) OpenTab(ctx, sessionKey, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenTab", reflect.TypeOf((*MockBrowserClient)(nil).OpenTab), ctx, sessionKey, url)
}

// Press mocks base method.
func (m *MockBrowserClient) Press(ctx context.Context, tabID, sessionKey, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Press", ctx, tabID, sessionKey, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Press indicates an expected call of Press.
func (mr *MockBrowserClientMockRecorder) Press(ctx, tabID, sessionKey, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Press", reflect.TypeOf((*MockBrowserClient)(nil).Press), ctx, tabID, sessionKey, key)
}

// Refresh mocks base method.
func (m *MockBrowserClient) Refresh(ctx context.Context, tabID, sessionKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, tabID, sessionKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Refresh indicates an expected call of Refresh.
func (mr *MockBrowserClientMockRecorder) Refresh(ctx, tabID, sessionKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockBrowserClient)(nil).Refresh), ctx, tabID, sessionKey)
}

// Screenshot mocks base method.
func (m *MockBrowserClient) Screenshot(ctx context.Context, tabID, sessionKey string, fullPage bool) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Screenshot", ctx, tabID, sessionKey, fullPage)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Screenshot indicates an expected call of Screenshot.
func (mr *MockBrowserClientMockRecorder) Screenshot(ctx, tabID, sessionKey, fullPage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Screenshot", reflect.TypeOf((*MockBrowserClient)(nil).Screenshot), ctx, tabID, sessionKey, fullPage)
}

// Scroll mocks base method.
func (m *MockBrowserClient) Scroll(ctx context.Context, tabID, sessionKey, direction string, amount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scroll", ctx, tabID, sessionKey, direction, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scroll indicates an expected call of Scroll.
func (mr *MockBrowserClientMockRecorder) Scroll(ctx, tabID, sessionKey, direction, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scroll", reflect.TypeOf((*MockBrowserClient)(nil).Scroll), ctx, tabID, sessionKey, direction, amount)
}

// Snapshot mocks base method.
func (m *MockBrowserClient) Snapshot(ctx context.Context, tabID, sessionKey string) (*browser.SnapshotResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", ctx, tabID, sessionKey)
	ret0, _ := ret[0].(*browser.SnapshotResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockBrowserClientMockRecorder) Snapshot(ctx, tabID, sessionKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockBrowserClient)(nil).Snapshot), ctx, tabID, sessionKey)
}

// Stats mocks base method.
func (m *MockBrowserClient) Stats(ctx context.Context, tabID, sessionKey string) (*browser.TabStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats", ctx, tabID, sessionKey)
	ret0, _ := ret[0].(*browser.TabStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockBrowserClientMockRecorder) Stats(ctx, tabID, sessionKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockBrowserClient)(nil).Stats), ctx, tabID, sessionKey)
}

// Type mocks base method.
func (m *MockBrowserClient) Type(ctx context.Context, tabID, sessionKey, ref, selector, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type", ctx, tabID, sessionKey, ref, selector, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockBrowserClientMockRecorder) Type(ctx, tabID, sessionKey, ref, selector, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockBrowserClient)(nil).Type), ctx, tabID, sessionKey, ref, selector, text)
}

// MockFilesystem is a mock of Filesystem interface.
type MockFilesystem struct {
	ctrl     *gomock.Controller
	recorder *MockFilesystemMockRecorder
	isgomock struct{}
}

// MockFilesystemMockRecorder is the mock recorder for MockFilesystem.
type MockFilesystemMockRecorder struct {
	mock *MockFilesystem
}

// NewMockFilesystem creates a new mock instance.
func NewMockFilesystem(ctrl *gomock.Controller) *MockFilesystem {
	mock := &MockFilesystem{ctrl: ctrl}
	mock.recorder = &MockFilesystemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilesystem) EXPECT() *MockFilesystemMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockFilesystem) Save(path string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", path, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockFilesystemMockRecorder) Save(path, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockFilesystem)(nil).Save), path, data)
}
